[workspace]
resolver = "3"
members = ["rkllm-api-sys", "rkllm-shell"]

[workspace.dependencies]
rkllm-api-sys = { version = "0.1.0", path = "./rkllm-api-sys" }
reqwest = { version = "0.12.18", features = ["blocking"] }
anyhow = "1.0.98"